### ISSUE TITLE
Not able to override collpase icon

### ISSUE THREAD

**Issue by Sudeepa1949** [marcantondahmen/sortable-tree#2]
can we modify the collapse icon to add our own custom icon, if yes HOW

**Comment by marcantondahmen** [comment]
I added an option to pass custom icons to the tree constructor in version 0.7 that can be used as follows:

```javascript
const tree = new SortableTree({
  nodes,
  element,
  icons: {
    collapsed: '+',
    open: '-',
  },
});
```

You can check out a full example on the demo page.

**Comment by Sudeepa1949** [comment]
I need to add my own svg file for collapse and open, How can I pass that

**Comment by Sudeepa1949** [comment]
can we add line Tree functionality here, can you suggest how can I add that

**Comment by marcantondahmen** [comment]
Lines can be easily added using plain CSS. I have added tree lines to the theme that is used on the demo page. You can use that one as a starting point.
