### ISSUE TITLE
Prevent drop node inside another node

### ISSUE THREAD

**Issue by kh4n998** [marcantondahmen/sortable-tree#7]
I see key _**disableSorting**_ to prevent drag & drop all node, so how can I prevent drop a node inside another specific node

**Comment by twright2010** [comment]
> I see key _**disableSorting**_ to prevent drag & drop all node, so how can I prevent drop a node inside another specific node

To prevent dropping on specific nodes, I use a data attribute to tag nodes that are not allowed to be dropped on, and in the SortableTree() initialization I use the confirm method to check for that tag.

So if you are dealing (for example) with a file system where you would not be wanting to drop files onto other files but only on folders, it would be as such:

When preparing the node data:
`data: { type: 'file' },`

` confirm: (source, target) => {
        return target.data.type != "file";
},`

**Comment by kh4n998** [comment]
> To prevent dropping on specific nodes, I use a data attribute to tag nodes that are not allowed to be dropped on, and in the SortableTree() initialization I use the confirm method to check for that tag.
> 
> So if you are dealing (for example) with a file system where you would not be wanting to drop files onto other files but only on folders, it would be as such:
> 
> When preparing the node data: `data: { type: 'file' },`
> 
> In the SortableTree() initializer: `confirm: (source, target) => { return target.data.type != "file"; },`

Oh thanks, that's all i need
