### ISSUE TITLE
observer not saved to private property

### ISSUE THREAD

**Issue by tanczosm** [marcantondahmen/sortable-tree#8]
I'm not exactly certain if my line of thinking is right here but I'm trying to update a tree by removing nodes from a previous tree before refreshing.  When using a state id it seems as though the mutation observer is kicking in from the existing tree and saving an empty state [] once I remove all the nodes, which crashes on load when I try to create the tree again.

Is this a bug?  In SortableTree.ts initStateObserver you have the following (const observer = instead of this.observer = ):
```typescript
		const observer = new MutationObserver(() => {
			saveState(stateId, this.parseTree(this.root));
		});
```

When you try and destroy the observer you have:
```typescript
	destroy(): void {
		this.observer.disconnect();
		this.observer = null;
	}
```

I can't find a place where this.observer is ever set.  bug?  I'm thinking initStateObserver should actually be:

```typescript

	initStateObserver(stateId: string): void {
		const observerOptions = {
			childList: true,
			attributes: true,
			subtree: true,
		};

		this.observer = new MutationObserver(() => {
			saveState(stateId, this.parseTree(this.root));
		});

		this.observer.observe(this.root, observerOptions);
	}

```

**Comment by tanczosm** [comment]
I forked the source, made the changes to use this.observer instead.  Now if I call the destroy() method I can disconnect the observers properly and not end up creating an empty state when I remove all the nodes from the tree and create the tree again.

So in essence, I can confirm this fix works.

Here is the fix, line 151 of SortableTree.ts:
```typescript
	initStateObserver(stateId: string): void {
		const observerOptions = {
			childList: true,
			attributes: true,
			subtree: true,
		};

		this.observer = new MutationObserver(() => {
			saveState(stateId, this.parseTree(this.root));
		});

		this.observer.observe(this.root, observerOptions);
	}
```

**Comment by marcantondahmen** [comment]
Thanks for reporting. It's fixed with the latest release.
